apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.port }}
      protocol: TCP
    - name: http
      port: {{ .Values.reverse_proxy_port }}
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.name }}
